# Generated by Django 4.2.7 on 2023-11-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catagory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='course.catagory'),
        ),
    ]
