# Generated by Django 4.2.7 on 2023-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_content_description_content_remarks_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sub_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
