# Generated by Django 4.2.7 on 2023-11-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_content_sub_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_item',
            name='rating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
