# Generated by Django 4.2.7 on 2023-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_bought_item_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
