# Generated by Django 4.2.7 on 2023-12-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
