# Generated by Django 4.2.7 on 2023-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_content_discount_course_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
