# Generated by Django 4.2.7 on 2023-12-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userinfo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
