# Generated by Django 4.2.7 on 2023-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userinfo_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ans',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ques',
            field=models.IntegerField(blank=True, default=0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
