# Generated by Django 4.2.7 on 2023-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userinfo_ans_userinfo_ques_alter_userinfo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ques',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
