# Generated by Django 4.2.7 on 2023-12-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userinfo_pic'),
        ('authentication', '0004_alter_userinfo_ques'),
    ]

    operations = [
    ]
